### ISSUE TITLE
Stuck on a strange screen that says 'Installing SRPQZ' when attempting to open the game

### ISSUE THREAD

**Issue by ZeGamingCuber** [Sereath/SRPQuarantineZone#1]
When I try to launch the game from the minecraft launcher after downloading the modpack via CurseForge I get a screen that I've literally never seen in any modpack before that say 'Installing SRPQZ' but there's no progress bar or anything and it just stays like that forever

**Comment by riengamer** [comment]
Hello
I just deleted something called "mod director" in the mods folder. Some lines appeared on screen when loading but as soon as the main menu popped up i never experienced any issues again. I don't know if you've already solved your problem, but just in case.
Hope this helps!

**Comment by Sereath** [comment]
(Had to be inactive for a while)

Yes, that is Mod Director downloading Optifine, not sure why some people can't seem to download it properly.

Valid issue so I'll leave it open.

**Comment by Sereath** [comment]
Shouldn't be an issue now, made Optifine's download optional (but still recommended).

**Comment by Sereath** [comment]
And it only seems to be a problem with the CurseForge launcher preventing downloads, so I recommend any other launcher, such as ATLauncher.
